DEF_STATUS(OK,                                      "OK")

DEF_STATUS(ERROR_CANT_INITIALIZE_LOG,               "ERROR_CANT_INITIALIZE_LOG")

DEF_STATUS(ERROR_CANT_READ_TREE_FROM_FILE,          "ERROR_CANT_READ_TREE_FROM_FILE")

DEF_STATUS(ERROR_CANT_WRITE_TREE_TO_FILE,           "ERROR_CANT_WRITE_TREE_TO_FILE")