DEF_STATUS(OK,                                      "OK")

DEF_STATUS(ERROR_CANT_INITIALIZE_LOG,               "ERROR_CANT_INITIALIZE_LOG")

DEF_STATUS(ERROR_CANT_READ_INPUT_FILE,              "ERROR_CANT_READ_INPUT_FILE")

DEF_STATUS(ERROR_MEMORY_ALLOC_ERROR,                "ERROR_MEMORY_ALLOC_ERROR")

DEF_STATUS(ERROR_COMPILATION_ERROR,                 "ERROR_COMPILATION_ERROR")

DEF_STATUS(ERROR_POP_NON_EXISTING_IR_ELEM,          "ERROR_POP_NON_EXISTING_IR_ELEM")

DEF_STATUS(ERROR_WRONG_NODE_IN_AST,                 "ERROR_WRONG_NODE_IN_AST")