DEF_STATUS(OK,                                      "OK")

DEF_STATUS(ERROR_CANT_INITIALIZE_LOG,               "ERROR_CANT_INITIALIZE_LOG")

DEF_STATUS(ERROR_CANT_READ_INPUT_FILE,              "ERROR_CANT_READ_INPUT_FILE")

DEF_STATUS(ERROR_CANT_OPEN_OUTPUT_FILE,             "ERROR_CANT_OPEN_OUTPUT_FILE")

DEF_STATUS(ERROR_DURING_TRANSLATION,                "ERROR_DURING_TRANSLATION")
