DEF_COMP_TREE_OP(1,     SEQ_EXEC)

DEF_COMP_TREE_OP(2,     DUMMY)

DEF_COMP_TREE_OP(3,     FUNC_DEF)

DEF_COMP_TREE_OP(4,     FUNC_DEF_HELPER)

DEF_COMP_TREE_OP(5,     LIST_CONNECTOR)

DEF_COMP_TREE_OP(6,     MAIN_PROG)



DEF_COMP_TREE_OP(51,     ASSIGN)

DEF_COMP_TREE_OP(52,     CMP_MORE)

DEF_COMP_TREE_OP(53,     CMP_LESS)

DEF_COMP_TREE_OP(54,     CMP_MORE_EQ)

DEF_COMP_TREE_OP(55,     CMP_LESS_EQ)

DEF_COMP_TREE_OP(56,     CMP_EQUAL)

DEF_COMP_TREE_OP(57,     CMP_NOT_EQ)



DEF_COMP_TREE_OP(101,     ADD)

DEF_COMP_TREE_OP(102,     SUB)

DEF_COMP_TREE_OP(103,     MUL)

DEF_COMP_TREE_OP(104,     DIV)



DEF_COMP_TREE_OP(201,     IF)

DEF_COMP_TREE_OP(202,     WHILE)

DEF_COMP_TREE_OP(203,     AND)

DEF_COMP_TREE_OP(204,     OR)

DEF_COMP_TREE_OP(205,     NOT)

DEF_COMP_TREE_OP(206,     ELSE)



DEF_COMP_TREE_OP(301,     SIN)

DEF_COMP_TREE_OP(302,     COS)

DEF_COMP_TREE_OP(303,     FLOOR)

DEF_COMP_TREE_OP(304,     DIFF)

DEF_COMP_TREE_OP(305,     SQRT)

DEF_COMP_TREE_OP(306,     LN)

DEF_COMP_TREE_OP(307,     EXP)

DEF_COMP_TREE_OP(308,     MINUS)



DEF_COMP_TREE_OP(401,     CALL_FUNC)

DEF_COMP_TREE_OP(402,     RETURN)

DEF_COMP_TREE_OP(403,     INPUT)

DEF_COMP_TREE_OP(405,     PRINT_NUM)

DEF_COMP_TREE_OP(406,     PRINT_CHAR)
